### ISSUE TITLE
JG fails with jQuery 4

### ISSUE THREAD

**Issue by jefftucker1952** [miromannino/Justified-Gallery#396]
This falls into the category of "future trouble." jQuery 4.0.0 is now in its second beta release. JustifiedGallery fails with this version of jQuery, with the following console error:

```
jquery.justifiedGallery.min.js:8 Uncaught TypeError: l.type is not a function
    at HTMLDivElement.<anonymous> (jquery.justifiedGallery.min.js:8:18834)
    at Function.each (jquery4.js:2:2876)
    at T.fn.init.each (jquery4.js:2:1386)
    at l.fn.justifiedGallery (jquery.justifiedGallery.min.js:8:18702)
    at index4.html:60:17
(anonymous) @ jquery.justifiedGallery.min.js:8
each @ jquery4.js:2
each @ jquery4.js:2
l.fn.justifiedGallery @ jquery.justifiedGallery.min.js:8
```

**Comment by miromannino** [comment]
Hello Jeff, I have already have a branch with a version 4.0 without jquery.

Just need to make extra sure is stable as thousands are using JG.

If you are able to test this branch it would be awesome

**Comment by jefftucker1952** [comment]
I'd be happy to test it, if I had even a clue about how to download the JS file. Remember, you're not talking to a "GitHub person." To me, GitHub is just a confusing maze. ;)

**Comment by kostenickj** [comment]
I can test it out, which branch is it? Really want to use this but dont want to add jquery to my site

**Comment by cfconsultancy** [comment]
where to find the beta version 4.0 without jquery ? So we can test it. Thx

**Comment by miromannino** [comment]
Version v4.0.0 doesn't use JQuery anymore, this shouldn't be a problem anymore
